name: ecosystem-transpiration
channels:
  - conda-forge
  - jnelson18
dependencies:
  - python
  - numpy
  - scipy
  - xarray
  - scikit-learn
  - matplotlib
  - transpiration_estimation_algorithm
  - sympy
  - netcdf4
  - jupyter
  - r-base=3.6
  - r-irkernel
